### PR TITLE
Added support order by RAND()

### PR DESCRIPTION
**Pull request by fmarchenko**

### CODE REVIEW

**Comment by tumb1er** [comment]
Looks like something is wrong in Django==1.8 and python-3.5

**Comment by tumb1er** [comment]
You need to override `DatabaseOperations.random_function_sql` function only. May be in other PR?

**Comment by fmarchenko** [comment]
Look django.db.models.sql.SQLCompiler.get_order_by line 252 and django.db.models.expressions.OrderBy.as_sql line 958

random_function_sql returns so what you need , but SQLCompiler affix sorting for RAND () that does not support Sphinx.

**Comment by tumb1er** [comment]
released with 0.4.0

**Comment by fmarchenko** [comment]
Thanks for commit my PR! :-)

**Pull request closed without merging**
